export enum MESSAGE_TYPE {
  HANDSHAKE = "HANDSHAKE",
  PLAYER_CONNECTED = "PLAYER_CONNECTED",
  AWAIT_ABILITY = "AWAIT_ABILITY",
  START = "START",
  PLAY_CARD = "PLAY_CARD",
  TAKE_CARD = "TAKE_CARD",
  SUBMIT_ABILITY = "SUBMIT_ABILITY",
  CANCEL_ABILITY = "CANCEL_ABILITY",
  GAME_OVER = "GAME_OVER",
  SET_NAME = "SET_NAME",
  NAME_ACCEPTED = "NAME_ACCEPTED",
  AWAIT_LEGION_CARD = "AWAIT_LEGION_CARD",
  THROW_LEGION_CARD = "THROW_LEGION_CARD",
  CHANGE_CARDS = "CHANGE_CARDS",
  READY_TO_PLAY = "READY_TO_PLAY",
  LEAVE_GAME = "LEAVE_GAME",
}

export type Message<T = object> = T & {
  type: MESSAGE_TYPE;
};
